INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_001', 'PIZZ-MARG-R', 'Margherita', 'Pizza', 'Regular', 12.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_002', 'PIZZ-MARG-L', 'Margherita', 'Pizza', 'Large', 14.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_003', 'PIZZ-DIAV-R', 'Diavola', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_004', 'PIZZ-DIAV-L', 'Diavola', 'Pizza', 'Large', 19.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_005', 'PIZZ-PARM-R', 'Parmigiana', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_006', 'PIZZ-PARM-L', 'Parmigiana', 'Pizza', 'Large', 18.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_007', 'PIZZ-QUAT-R', 'Quattro Formaggi', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_008', 'PIZZ-QUAT-L', 'Quattro Formaggi', 'Pizza', 'Large', 19.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_009', 'PIZZ-NAPO-R', 'Napolitana', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_010', 'PIZZ-NAPO-L', 'Napolitana', 'Pizza', 'Large', 18.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_011', 'PIZZ-PEPP-R', 'Pepperoni', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_012', 'PIZZ-PEPP-L', 'Pepperoni', 'Pizza', 'Large', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_013', 'PIZZ-SEAF-R', 'Seafood', 'Pizza', 'Regular', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_014', 'PIZZ-SEAF-L', 'Seafood', 'Pizza', 'Large', 20.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_015', 'PIZZ-HAWA-R', 'Hawaiian', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_016', 'PIZZ-HAWA-L', 'Hawaiian', 'Pizza', 'Large', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_017', 'SIDE-GARL-R', 'Garlic Bread', 'Side', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_018', 'SIDE-CHIC-R', 'Chicken Wings', 'Side', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_019', 'SIDE-BREA-R', 'Breadsticks', 'Side', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_020', 'SIDE-CEAS-R', 'Ceasar Salad', 'Side', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_021', 'DESS-ICE-CHOC', 'Chocolate Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_022', 'DESS-ICE-VANI', 'Vanilla Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_023', 'DESS-ICE-STRA', 'Strawberry Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_024', 'DESS-ICE-PIST', 'Pistachio Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_025', 'DESS-CHOC-BROW', 'Chocolate Brownie', 'Dessert', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_026', 'DESS-BANO-PIE', 'Banoffee Pie', 'Dessert', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_027', 'DESS-FRUI-SALA', 'Fruit Salad', 'Dessert', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it_028', 'BEVA-CC-REG33', 'Coca Cola', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it029', 'BEVA-CC-REG1500', 'Coca Cola', 'Beverage', '1.5l', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it030', 'BEVA-CC-DIE33', 'Diet Coke', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it031', 'BEVA-CC-DIE1500', 'Diet Coke', 'Beverage', '1.5l', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it032', 'BEVA-7U-REG33', '7 Up', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it033', 'BVA-7U-REG1500', '7 Up', 'Beverage', '1.5l', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it001', 'PIZZ-MARG-R', 'Margherita', 'Pizza', 'Regular', 12.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it002', 'PIZZ-MARG-L', 'Margherita', 'Pizza', 'Large', 14.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it003', 'PIZZ-DIAV-R', 'Diavola', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it004', 'PIZZ-DIAV-L', 'Diavola', 'Pizza', 'Large', 19.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it005', 'PIZZ-PARM-R', 'Parmigiana', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it006', 'PIZZ-PARM-L', 'Parmigiana', 'Pizza', 'Large', 18.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it007', 'PIZZ-QUAT-R', 'Quattro Formaggi', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it008', 'PIZZ-QUAT-L', 'Quattro Formaggi', 'Pizza', 'Large', 19.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it009', 'PIZZ-NAPO-R', 'Napolitana', 'Pizza', 'Regular', 16.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it010', 'PIZZ-NAPO-L', 'Napolitana', 'Pizza', 'Large', 18.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it011', 'PIZZ-PEPP-R', 'Pepperoni', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it012', 'PIZZ-PEPP-L', 'Pepperoni', 'Pizza', 'Large', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it013', 'PIZZ-SEAF-R', 'Seafood', 'Pizza', 'Regular', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it014', 'PIZZ-SEAF-L', 'Seafood', 'Pizza', 'Large', 20.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it015', 'PIZZ-HAWA-R', 'Hawaiian', 'Pizza', 'Regular', 15.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it016', 'PIZZ-HAWA-L', 'Hawaiian', 'Pizza', 'Large', 17.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it017', 'SIDE-GARL-R', 'Garlic Bread', 'Side', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it018', 'SIDE-CHIC-R', 'Chicken Wings', 'Side', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it019', 'SIDE-BREA-R', 'Breadsticks', 'Side', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it020', 'SIDE-CEAS-R', 'Ceasar Salad', 'Side', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it021', 'DESS-ICE-CHOC', 'Chocolate Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it022', 'DESS-ICE-VANI', 'Vanilla Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it023', 'DESS-ICE-STRA', 'Strawberry Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it024', 'DESS-ICE-PIST', 'Pistachio Ice Cream', 'Dessert', 'Regular', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it025', 'DESS-CHOC-BROW', 'Chocolate Brownie', 'Dessert', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it026', 'DESS-BANO-PIE', 'Banoffee Pie', 'Dessert', 'Regular', 7.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it027', 'DESS-FRUI-SALA', 'Fruit Salad', 'Dessert', 'Regular', 5.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it028', 'BEVA-CC-REG33', 'Coca Cola', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it029', 'BEVA-CC-REG1500', 'Coca Cola', 'Beverage', '1.5l', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it030', 'BEVA-CC-DIE33', 'Diet Coke', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it031', 'BEVA-CC-DIE1500', 'Diet Coke', 'Beverage', '1.5l', 6.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it032', 'BEVA-7U-REG33', '7 Up', 'Beverage', '33cl', 3.00);
INSERT INTO `item` (`item_id`, `sku`, `item_name`, `item_cat`, `item_size`, `item_price`) VALUES ('it033', 'BVA-7U-REG1500', '7 Up', 'Beverage', '1.5l', 6.00);
