INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (1, '607 Trials End Road', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (2, '25 Cliffside Drive', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (3, '56 Concord Road', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (4, '82 Lookout Lountain Drive', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (5, '21 Carver Lane', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (6, '61 Plymouth Lane', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (7, '265 Slater Street', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (8, '159 Adams Street', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (9, '66 Pine Street', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (10, '18 Cambridge Street', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (11, '310 Timrod Road', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (12, '44 Downey Drive', NULL, 'Manchester', '6040');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (13, '31 Buckland Hills Drive', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (14, '194 Buckland Hills Drive', NULL, 'Manchester', '6042');
INSERT INTO `address` (`add_id`, `delivery_address1`, `delivery_address2`, `delivery_city`, `delivery_zipcode`) VALUES (15, '29 Lucian Street', NULL, 'Manchester', '6040');
