INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING001', 'Pizza dough ball (8 pack)', 2000, 'grams', 4);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING002', 'Tomato sauce', 4500, 'grams', 4);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING003', 'Mozarella cheese', 2500, 'grams', 14);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING004', 'Dried oregano', 500, 'grams', 6);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING005', 'Spicy salami', 3500, 'grams', 38);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING006', 'Chilli pepper', 1000, 'grams', 6);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING007', 'Eggplant', 1000, 'grams', 2);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING008', 'Parmesan cheese', 2500, 'grams', 19);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING009', 'Gorgonzola cheese', 3500, 'grams', 28);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING010', 'Ricotta cheese', 1500, 'grams', 4);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING011', 'Anchovies', 1000, 'grams', 11);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING012', 'Capers', 1000, 'grams', 4);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING013', 'Pepperoni', 2500, 'grams', 24);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING014', 'Shrimp', 1000, 'grams', 9);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING015', 'Tuna', 2000, 'grams', 8);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING016', 'Calamari', 2500, 'grams', 29);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING017', 'Ham', 5000, 'grams', 32);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING018', 'Pineapple', 5000, 'grams', 6);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING019', 'Garlic and parsley butter', 3000, 'grams', 52);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING020', 'Chicken Wings', 6000, 'grams', 70);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING021', 'Rotisserie chicken pieces', 5000, 'grams', 34);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING022', 'Croutins', 1250, 'grams', 5);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING023', 'Romain lettuce', 7500, 'grams', 14);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING024', 'Caesar dressing', 3800, 'grams', 18);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING025', 'Vanilla ice cream', 4500, 'mililitres', 15);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING026', 'Chocolate ice cream', 4500, 'mililitres', 15);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING027', 'Strawberry ice cream', 4500, 'mililitres', 15);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING028', 'Breadsticks', 3500, 'grams', 8);
INSERT INTO `ingredient` (`ing_id`, `ing_name`, `ing_weight`, `ing_meas`, `ing_price`) VALUES ('ING029', 'Ceasar Salad', 4000, 'grams', 10);
